## CIND830 - Python Programming for Data Science  
### Assignment 3 (10% of the final grade)
### Due on December 10, 2020 11:59 PM
### Name: Tasdeed Aziz
### ID:500945638

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Jupyter Notebook.

Use the JupyterHub server on the Google Cloud Platform,
provided by your designated instructor, for this assignment.
Complete the assignment by inserting your Python code wherever you see the string
"#INSERT YOUR ANSWER HERE." or "##CODE HERE##"

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1:

**a)** Write a code segment to create and print a two-dimensional 5x4 array (i.e. grid). The elements of the grid should be randomly selected from the inclusive interval \[-50, 50\].

In [27]:
import random
import numpy as np

matrix = np.random.randint(-50,50,(5,4))
print(matrix)

[[-31  -7 -34  40]
 [  8   3 -20   1]
 [ 30   9 -11  -1]
 [ 31 -22  18 -49]
 [ 48 -25  47  25]]


**b)** Write a code segment that searches the `Grid` object in `Q1a` for all the negative integers, and prints them.

In [28]:
for row in matrix:
    for column in row:
        if column < 0:
            print(column)
    
        

-31
-7
-34
-20
-11
-1
-22
-49
-25


**c)** Given that `iList = [1, -1, 2, -2]`, add each element of `iList` to its corresponding element of `Q1a` `Grid` row-wise.  

For example, if the Grid is equal to: $$\begin{pmatrix} 1 & 2 & 1 & 1 \\ 3 & 0 & 1 & 6 \\ 0 & 2 & 4 & 6 \\ 4 & 5 &0 & 2 \\ 3 & 6 & 4 & 3 \end{pmatrix}$$

Then the output should be:
$$\begin{pmatrix} 1+1 & 2-1 & 1+2 & 1-2 \\ 3+1 & 0-1 & 1+2 & 6-2 \\ 0+1 & 2-1 & 4+2 & 6-2 \\ 4+1 & 5-1 &0+2 & 2-2 \\ 3+1 & 6-1 & 4+2 & 3-2 \end{pmatrix}$$

In [29]:
iList = [1,-1,2,-2]
addition = matrix + iList
print(addition)

[[-30  -8 -32  38]
 [  9   2 -18  -1]
 [ 31   8  -9  -3]
 [ 32 -23  20 -51]
 [ 49 -26  49  23]]


**d)** Write a code segment that creates a ragged grid with three rows.  The first row contains 2 positions, the second row contains 4 positions, and the third row contains 6 positions. 

In [43]:
matrix2 = [[1, 2], [1,2,3, 4], [1,2,3,4,5,6]]
for row in range(len(matrix2)):
    for column in range(len(matrix2[row])):
        print(matrix2[row][column], end = ' ')
    print()

1 2 
1 2 3 4 
1 2 3 4 5 6 


*****



### Question 2:
A search algorithm `iSearch` and a variable `ilist` have been defined as follows:




In [21]:
def iSearch(target, lyst):
    left = 0
    right = len(lyst) - 1
    while left <= right:
        midpoint = (left + right) // 2
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
        else:
            left = midpoint + 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]

**a)**  If the target element is `11`, trace the values of the variables `left`, `right`, and `midpoint` after applying the `iSearch` algorithm to the `iList` structure. 



In [2]:
def iSearch(target, lyst):
    left = 0
    print('left:',left)
    right = len(lyst) - 1
    print('right:',right)
    while left <= right:
        midpoint = (left + right) // 2
        print('Midpoint:',midpoint)
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
            print('Right:', right)
        else:
            left = midpoint + 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]


search = iSearch(11,iList)
print('Target Position:',search)

left: 0
right: 10
Midpoint: 5
Right: 4
Midpoint: 2
Right: 1
Midpoint: 0
Target Position: 0


**b)**  Repeat the tracing process in `Q1a` for target element `55`.

In [41]:
def iSearch(target, lyst):
    left = 0
    print('left:',left)
    right = len(lyst) - 1
    print('right:',right)
    while left <= right:
        midpoint = (left + right) // 2
        print('Midpoint:',midpoint)
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            right = midpoint - 1
            print('Right:',right)
        else:
            left = midpoint + 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]


search = iSearch(55,iList)
print('Target Position:',search)

left: 0
right: 10
Midpoint: 5
Target Position: 5


**c)**  Why does the iSearch algorithm run faster in `Q1b` scenario than in `Q1a` scenario?

In [ ]:
#INSERT YOUR ANSWER HERE.
'''In Q1b scenario the target is in middle, the target matches the midpoint value
and the alogrithm returns the position of taget item without searching any further or iterating.
The complexity of this scenario is in order of O(1) as it takes a constant number.In Q1a the target is
in beginning of the list, so the algorithms keeps searching till the value matches the midpoint value.
As a result computation is much faster in Q1b than in Q1a.'''

**d)** Modify the `iSearch` algorithm, so it can run in `Q1a` scenario as fast as it does in `Q1b` scenario.

In [26]:
def iSearch(target, lyst):
    left = 0
    print('left:',left)
    right = len(lyst) - 1
    print('right:',right)
    while left <= right:
        midpoint = (left + right) // 2
        print('Midpoint:',midpoint)
        if target == lyst[midpoint]:
            return midpoint
        elif target < lyst[midpoint]:
            return lyst.index(target)
        else:
            left = midpoint + 1
    return -1

iList = [11, 20, 29, 33, 41, 55, 56, 62, 66, 74, 88]


search =iSearch(11,iList)
print('Target Position:',search)


left: 0
right: 10
Midpoint: 5
Target Position: 0


**e)** For a problem of size $n$, if algorithm `X` performs $n^4$ instructions, and algorithm `Y` performs $2^n$ instructions.  At what point does one of the algorithms begin to be more efficient and perform better than the other? Justify your answer.

In [ ]:
'''The algorithm X is more efficient at a point where the size of n increases. The algorithm Y is 
an exponential, which is not effiecent to be perform on large size of n due to higher order of complexity.'''

*****

### Question 3:



Emulate the stack behaviour using the list data structure.

**a)** Complete the methods of the following `Stack` class according to their description

In [5]:
class Stack:
  def __init__(self):
    """ Initialize a new stack """
    self.elements = []
  def push(self, new_item):
    """ Append the new item to the stack """
    self.elements.append(new_item)
  def pop(self):
    """ Remove and return the last item from the stack """
    return self.elements.pop()
  def size(self):
    """ Return the total number of elements in the stack """
    return len(self.elements)
  def is_empty(self):
    """ Return True if the stack is empty and False if it is not empty """
    return self.elements == []
  def peek(self):
    """ Return the element at the top of the stack or return None if the stack is empty """
    if not self. is_empty():
        return self.elements[-1]
    
  def get_stack(self): ## testing the elements
    return self.elements


**b)** Use the `Stack` class that you defined in `Q3a` to complete the code of the `is_valid()` function, which checks whether the order of the brackets of an arithmetic expression is correct. Some examples are given below:

In [3]:
exp1 = "(2+3)+(1-5)" # True
exp2 = "((3*2))*(7/3))" # False
exp3 = "(3*5))]" # False
#test1 = '()'
#test2 = '()]}'
#test3 = '}{}'

In [6]:
def is_valid(exp):
  """ Check the order of the brackets
      Returns True or False
  """
  opening = ['(', '[', '{']
  closing = [')', ']', '}']
  s = Stack()
  for symbols in exp:
    if symbols in opening:
        s.push(symbols)
    elif symbols in closing:
        if s.is_empty():
            return False
        top = s.pop()
        if symbols == ')' and top != '(':
            return False
        elif symbols == ']' and top != '[':
            return False
        elif symbols == '}' and top != '}':
            return False
             
  return s.is_empty()
  
print(is_valid(exp1))
print(is_valid(exp2))
print(is_valid(exp3))
#print(is_valid(test1))
#print(is_valid(test2))
#print(is_valid(test3))

True
False
False


**c)** Use the `Stack` class that you defined in `Q3a` to complete the code of the `count_pairs()` function, which returns the number of the valid bracket pairs of an arithmetic expression. Some examples are given below:

In [7]:
exp1 = "(2+3)+(1-5)" # 2 pairs
exp2 = "((([()])))" # 5 pairs
exp3 = "[([])" # 2 pairs

In [8]:
def count_pairs(exp):
  """ Count the valid number of brackets
      Returns the total number of valid brackets in the string
  """
  opening = ['(', '[', '{']
  closing = [')', ']', '}']
  s = Stack()
  pairs = 0 
  for symbols in exp:
        if symbols in opening:
            s.push(symbols)
        elif symbols in closing:
            if s.is_empty():
                pass
            else:
                s.pop()
                pairs +=1
                
  return  pairs

print(count_pairs(exp1),'pairs')
print(count_pairs(exp2),'pairs')
print(count_pairs(exp3),'pairs')

2 pairs
5 pairs
2 pairs


### Question 4:
According to each method's documentation, complete the code of the `TextProcessor` class and its subclass `TextAnalyzer`.

In [9]:
class TextProcessor:
  def __init__(self, text):
    self.text = text
  def setStopWords(self,stopWords):
    ''' set stop words as recieved in the parameters '''
    self.stopWords = stopWords
  def getStopWords(self):
    ''' return stop words '''
    return self.stopWords
  def getUniqWords(self):
    return set(self.__text.split())
  def getFilteredText(self):
    ''' remove filter words from the text 
        return filtered text
    '''
    filtered_words = []
    for word in self.text.split():
        if word not in self.stopWords:
            filtered_words.append(word)
    return filtered_words
    
class TextAnalyzer(TextProcessor):
  def __init__(self,text):
    ''' Construct the class '''
    self.text = text
    
  def getWordFrequency(self):
    
    ''' Call the getFilteredText() method
        Create a dictionary of words
        key = word and value= frequency
        return the dictionary
    '''
    filtered_words = self.getFilteredText()
    dictFreq = {}
    for i in filtered_words:
        dictFreq[i] = filtered_words.count(i)
    return dictFreq
    

In [10]:
ta = TextAnalyzer("a quick brown fox " + 
                  "a quick brown fox jumps " + 
                  "a quick brown fox jumps over " + 
                  "a quick brown fox jumps over the " + 
                  "a quick brown fox jumps over the lazy " + 
                  "a quick brown fox jumps over the lazy dog")

ta.setStopWords(['a','the'])
#print(ta.stopWords)

ta.getWordFrequency()


{'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'lazy': 2, 'dog': 1}

Verify the correctness of your code using the following steps:

1. Instantiate the `TextAnalyzer` class by creating an object called `ta` as follows:

`ta = TextAnalyzer("a quick brown fox " + 
                  "a quick brown fox jumps " + 
                  "a quick brown fox jumps over " + 
                  "a quick brown fox jumps over the " + 
                  "a quick brown fox jumps over the lazy " + 
                  "a quick brown fox jumps over the lazy dog")`

2. Assign a list of stop words using the `setStopWords()` method:
`ta.setStopWords(['a', 'the'])`

3. Count the occurrences of each word using the `getWordFrequency()` method:
`ta.getWordFrequency()`

4. The output should be as follows
`{'quick': 6, 'brown': 6, 'fox': 6, 'jumps': 5, 'over': 4, 'lazy': 2, 'dog': 1}}`


#### This is the end of assignment 3